export enum NotificationType {
  CONTRIBUTION = 'CONTRIBUTION',
  MILESTONE = 'MILESTONE',
  DEADLINE = 'DEADLINE',
  SYSTEM = 'SYSTEM',
  POLICY_PURCHASED = 'POLICY_PURCHASED',
  CLAIM_CREATED = 'CLAIM_CREATED',
  CLAIM_APPROVED = 'CLAIM_APPROVED',
  CLAIM_REJECTED = 'CLAIM_REJECTED',
  CLAIM_PAID = 'CLAIM_PAID',
}
